language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    - platformio run

notifications:
  email:
    on_success: change
    on_failure: change
